Citizen.CreateThread(function()
	-- Police/EMS
	AddTextEntry('psp_bmwgs', 'BMW PD Bike')
	AddTextEntry('emsnspeedo', 'Speedo Ambulance')
	AddTextEntry('m5rb_vv', 'Unmarked BMW M5')
	AddTextEntry('um18charger', 'Unmarked Dodge Charger')
	AddTextEntry('lsfdfpiu', 'Fire Explorer')
	AddTextEntry('ems2018charger', 'EMS Charger')

	-- Job cars
	AddTextEntry('golfmk6', 'Golf Mk6')
	AddTextEntry('m3e36', 'BMW M3 E36')
	AddTextEntry('nspeedo', 'Vapid Speedo Express')

	--First Pack (4 Doors)
	AddTextEntry('G632019', '2019 Mercedes G63')
	AddTextEntry('mers18', 'Renault Megane')
	AddTextEntry('a8fsi', 'Audi A8')
	AddTextEntry('kiagt', 'Kia Stinger')

	-- Second Pack (Boosting)
	AddTextEntry('subwrx', '2004 Subaru Impreza WRX STI')
	AddTextEntry('trhawk', '2018 Jeep Grand Cherokee Trackhawk Series IV')
	AddTextEntry('rcf', '2015 Lexus RCF')
	AddTextEntry('honcrx91', 'Honda CRX SiR 1991')
	AddTextEntry('gtr96', '1996 McLaren F1 GTR')
	AddTextEntry('gtr', '2017 Nissan GTR')
	AddTextEntry('f812', '2018 Ferrari 812 Superfast')
	AddTextEntry('cp9a', 'Mitsubishi Lancer Evo VI T.M.E')
	AddTextEntry('majfd', 'Mazda RX-7 FD')
	AddTextEntry('rsvr16', 'Range Rover Sport SVR 2016')
end)